
name: Study lyte Coverage Badge

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: ./.github/wiki/
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          python -m pip install pytest coverage genbadge[coverage]
          python setup.py install

      - name: Create Badges
        shell: bash
        run: |
          coverage run --source study_lyte -m pytest
          coverage xml
          genbadge coverage -i coverage.xml -o .github/wiki/coverage.svg

      - name: Push to wiki
        shell: bash
        run: |
          cd ./.github/wiki/
          git add --all
          git diff-index --quiet HEAD && exit
          git config --local user.name  "GitHub Action"
          git config --local user.email "action@github.com"
          git commit --amend --no-edit   && git push --force-with-lease || \
          git commit -m"Update coverage" && git push
